CURRENT_SEASON = 2022
STANDING_OUTPUT_PATH = f"./{CURRENT_SEASON}_standings.json"
PLAYER_BASIC_STATS_OUTPUT_PATH = f"./{CURRENT_SEASON}_player_season_totals.json"
PLAYER_ADVANCED_STATS_OUTPUT_PATH = f"./{CURRENT_SEASON}_player_advanced_season_totals.json"